changelog:
  categories:
  - title: Breaking Changes
    labels:
    - breaking-change
  - title: Global Updates
    labels:
    - global-updates
  - title: Features
    labels:
    - feature
    - enhancement
  - title: Bug fixes
    labels:
    - bug
    - patch
    - bugfix
  - title: Hot Fixes
    labels:
    - hotfix
  - title: QA
    labels:
    - qa
  - title: Docs
    labels:
    - docs
    - documentation
  - title: Refactor
    labels:
    - refactor
  - title: Config
    labels:
    - config
    - configuration
    - github-workflow
    - dev-workflow
  - title: Other Changes
    labels:
       - "*"
