name: Shopify Lighthouse CI
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
  push:
    branches:
      - performance-testing

jobs:
  lhci:
    name: Lighthouse
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.SHOP_STORE }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          # password: ${{ secrets.SHOP_PASSWORD }} (needed when store is password protected)
          # collection_handle: (use to test on specific collection page)
          # product_handle: (use to test on specific product page)
          lhci_min_score_performance: 0.9
          lhci_min_score_accessibility: 0.9
